[CI] Add PR validation
Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -126,13 +126,65 @@ jobs:
           VALIDATE_RENOVATE: true # does not support newest renovate config
           VALIDATE_SHELL_SHFMT: true
           VALIDATE_XML: true
+  validate-pr:
+    name: Validate PR Metadata
+    runs-on: ubuntu-24.04
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          fetch-depth: 0
+          persist-credentials: 'false'
+
+      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
+        with:
+          python-version: "3.13"
+
+      - name: Set up chart-testing
+        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
+        with:
+          # renovate: github=helm/chart-testing
+          version: v3.14.0
+
+      - name: Run chart-testing (list-changed)
+        id: list-changed
+        run: |
+          changed="$(ct list-changed --config .github/linters/ct.yaml)"
+          if [[ -n "$changed" ]]; then
+            echo "changed=true" >> "$GITHUB_OUTPUT"
+            echo "changed_list=\"${changed//$'\n'/ }\"" >> "$GITHUB_OUTPUT"
+          fi
+
+      - name: check for multiple chart changes
+        if: steps.list-changed.outputs.changed == 'true'
+        run: |
+          COUNT=$(echo $CHANGED_LIST | wc -w)
+          if [ "$COUNT" -gt 1 ]; then
+            echo "Error: Multiple charts changed ($COUNT). Please create separate PRs for each chart."
+            exit 1
+          fi
+        env:
+          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
+
+      - name: check for PR title format
+        if: steps.list-changed.outputs.changed == 'true'
+        run: |      
+          if [[ "$PR_TITLE" != "[${CHANGED_LIST##*/}] "* ]]; then
+            echo "PR title must start with '[${CHANGED_LIST##*/}] '." >&2
+            exit 1
+          fi
+        env:
+          CHANGED_LIST: ${{ steps.list-changed.outputs.changed_list }}
 
   renovate-auto-merge:
     name: Auto-approve PRs from Renovate
     runs-on: ubuntu-24.04
     needs:
       - lint-test
-      #- check-codeowners-maintainers
+      - check-codeowners-maintainers
+      - validate-pr
       - super-linter
     if: >-
       github.event.pull_request.head.repo.full_name == github.repository
